defmodule HacktuiAgent.HermesLocal do
  @moduledoc """
  Deterministic local artifact generation for the demo path.

  This is not an LLM-backed Hermes runtime.
  It is a bounded local artifact generator for demo reliability.
  """

  @artifact_dir "demo_artifacts"

  @spec summarize(String.t(), Jido.Agent.t()) :: map()
  def summarize(case_id, agent) do
    correlation = agent.state.correlation || %{}
    report = agent.state.report_draft || %{}

    recommendation =
      if Map.get(correlation, :shared_indicators, []) == [] do
        "Continue monitoring. No simulated action is proposed."
      else
        "Request approval for SIMULATED containment of host-42."
      end

    %{
      case_id: case_id,
      matched_alert_ids: Map.get(correlation, :matched_alert_ids, []),
      shared_indicators: Map.get(correlation, :shared_indicators, []),
      summary: Map.get(report, :summary, "No summary available."),
      recommendation: recommendation,
      note: "Hermes-local deterministic summary artifact"
    }
  end

  @spec write_artifacts!(map()) :: map()
  def write_artifacts!(summary) do
    File.mkdir_p!(@artifact_dir)

    summary_path = Path.join(@artifact_dir, "#{summary.case_id}-summary.md")
    skill_path = Path.join(@artifact_dir, "#{summary.case_id}-skill.md")

    File.write!(summary_path, summary_markdown(summary))
    File.write!(skill_path, skill_markdown(summary))

    %{summary_path: summary_path, skill_path: skill_path}
  end

  defp summary_markdown(summary) do
    """
    # #{summary.case_id} Summary

    Generated by Hermes-local deterministic summary generation.

    Summary:
    #{summary.summary}

    Matched alerts:
    #{Enum.join(summary.matched_alert_ids, ", ")}

    Shared indicators:
    #{Enum.join(summary.shared_indicators, ", ")}

    Recommendation:
    #{summary.recommendation}
    """
  end

  defp skill_markdown(summary) do
    """
    # #{summary.case_id} Investigation Skill

    Generated by Hermes-local deterministic skill generation.

    Trigger:
    - repeated investigation for #{summary.case_id}

    Steps:
    1. Load investigation context from the hub read models.
    2. Correlate shared indicators across alerts and timeline entries.
    3. Draft an analyst-facing summary.
    4. If indicators remain suspicious, request approval for SIMULATED containment.

    Known indicators:
    - #{Enum.join(summary.shared_indicators, "
- ")}
    """
  end
end
